### PR TITLE
Add new features

### PR DESCRIPTION
**Pull request by NikoGrano**
## Added
- rDNS Support for Master and Worker nodes (IPv4)
- rDNS Support for Floating IPv4
- FQDN for Workers and Master

## Changed
- Quicker first step, do not wait for reboot

## Fixed
- Invalid Yaml on `roles/metal-lb/tasks/main.yaml` due `:`

### CODE REVIEW

**Comment by NikoGrano** [comment]
@rvasilev I'm requesting your review, approval and merge.

**Comment by NikoGrano** [comment]
Seems like it fails after I recreated everything. I need to make some changes.

**Comment by NikoGrano** [comment]
Okey, now it should be fine.

**Comment by NikoGrano** [comment]
Okey, so now I have issue, which I'm not able to resolve myself.

This gets stuck on `TASK [metal-lb : Wait Tiller available]` and `kubectl get nodes` starts return `No reosurces found in default namespace`

I will try investigate this, but is there something, to do with hostnames?
@rvasilev

**Comment by NikoGrano** [comment]
**DEBUG Details**

So, I did do some debugging. I SSH as root into the master node and ran `kubectl get events` and it shows some interesting data...

```
root@master:~# kubectl --kubeconfig /etc/kubernetes/admin.conf get events
LAST SEEN   TYPE     REASON                                                                      OBJECT        MESSAGE
3m55s       Normal   NodeHasSufficientMemory                                                     node/master   Node master status is now: NodeHasSufficientMemory
3m55s       Normal   NodeHasNoDiskPressure                                                       node/master   Node master status is now: NodeHasNoDiskPressure
3m55s       Normal   NodeHasSufficientPID                                                        node/master   Node master status is now: NodeHasSufficientPID
3m41s       Normal   Starting                                                                    node/master   Starting kubelet.
2m50s       Normal   NodeHasSufficientMemory                                                     node/master   Node master status is now: NodeHasSufficientMemory
2m50s       Normal   NodeHasNoDiskPressure                                                       node/master   Node master status is now: NodeHasNoDiskPressure
2m50s       Normal   NodeHasSufficientPID                                                        node/master   Node master status is now: NodeHasSufficientPID
3m40s       Normal   NodeAllocatableEnforced                                                     node/master   Updated Node Allocatable limit across pods
3m25s       Normal   RegisteredNode                                                              node/master   Node master event: Registered Node master in Controller
3m23s       Normal   Starting                                                                    node/master   Starting kube-proxy.
2m51s       Normal   Deleting Node master because it's not present according to cloud provider   node/master   Node master event: DeletingNode
2m50s       Normal   RemovingNode                                                                node/master   Node master event: Removing Node master from Controller
3m19s       Normal   Starting                                                                    node/node-1   Starting kubelet.
2m5s        Normal   NodeHasSufficientMemory                                                     node/node-1   Node node-1 status is now: NodeHasSufficientMemory
2m5s        Normal   NodeHasNoDiskPressure                                                       node/node-1   Node node-1 status is now: NodeHasNoDiskPressure
2m5s        Normal   NodeHasSufficientPID                                                        node/node-1   Node node-1 status is now: NodeHasSufficientPID
3m19s       Normal   NodeAllocatableEnforced                                                     node/node-1   Updated Node Allocatable limit across pods
3m15s       Normal   RegisteredNode                                                              node/node-1   Node node-1 event: Registered Node node-1 in Controller
2m51s       Normal   Deleting Node node-1 because it's not present according to cloud provider   node/node-1   Node node-1 event: DeletingNode
2m50s       Normal   RemovingNode                                                                node/node-1   Node node-1 event: Removing Node node-1 from Controller
2m12s       Normal   Starting                                                                    node/node-1   Starting kube-proxy.
3m20s       Normal   Starting                                                                    node/node-2   Starting kubelet.
2m5s        Normal   NodeHasSufficientMemory                                                     node/node-2   Node node-2 status is now: NodeHasSufficientMemory
2m5s        Normal   NodeHasNoDiskPressure                                                       node/node-2   Node node-2 status is now: NodeHasNoDiskPressure
2m6s        Normal   NodeHasSufficientPID                                                        node/node-2   Node node-2 status is now: NodeHasSufficientPID
3m19s       Normal   NodeAllocatableEnforced                                                     node/node-2   Updated Node Allocatable limit across pods
3m15s       Normal   RegisteredNode                                                              node/node-2   Node node-2 event: Registered Node node-2 in Controller
3m12s       Normal   Starting                                                                    node/node-2   Starting kube-proxy.
2m51s       Normal   Deleting Node node-2 because it's not present according to cloud provider   node/node-2   Node node-2 event: DeletingNode
2m50s       Normal   RemovingNode                                                                node/node-2   Node node-2 event: Removing Node node-2 from Controller
```

**Comment by NikoGrano** [comment]
Okay, so the issue is caused by having FQDN in the hosts.

**Review by rvasilev — APPROVED** [review]

**Review by rvasilev — APPROVED** [review]

**Review by rvasilev — APPROVED** [review]

**Review by rvasilev — APPROVED** [review]

**Comment by NikoGrano** [comment]
@rvasilev Feel free to merge.

**Pull request merged**
