### PR TITLE
Add support to add more nodes after creating the cluster

### PR DESCRIPTION
**Pull request by NikoGrano**

### CODE REVIEW

**Comment by NikoGrano** [comment]
I need you opinion on this

**Review by rvasilev — CHANGES_REQUESTED** [review]
looks like "script/gitlab" should be removed from "scale cluster" PR

**Comment by rvasilev** [comment]
https://github.com/linux-noob/hcloud-k8s/pull/11/commits/a28dc13c85ea8bc091265bcb72d75076210a6fef merged

**Comment by NikoGrano** [comment]
yeh, I was pushing gametactic related stuff there. Good you took only part which I proposed.

**Pull request closed without merging**
